const TRADUCCIONES = {
  es: {
    // -- Navigation --
    nav_dashboard: 'Dashboard',
    nav_ganaderia: 'Ganadería',
    nav_cultivos: 'Cultivos',
    nav_lotes: 'Lotes y Mapas',
    nav_operaciones: 'Operaciones',
    nav_grupos_manejo: 'Grupos Manejo',
    nav_plantillas: 'Plantillas',
    nav_planeacion: 'Planeación',
    nav_equipos: 'Equipos/Maquinaria',
    nav_alertas: 'Alertas',
    nav_farmacia: 'Farmacia',
    nav_agua: 'Agua',
    nav_alimentacion: 'Alimentación',
    nav_picicultura: 'Picicultura',
    nav_suelos: 'Suelos/Análisis',
    nav_sensores: 'Sensores',
    nav_forestal: 'Forestal',
    nav_especies: 'Especies',
    nav_consolidado: 'Consolidado',
    nav_contabilidad: 'Contabilidad',
    nav_nomina: 'Nómina',
    nav_inventario: 'Inventario',
    nav_trabajadores: 'Trabajadores',
    nav_mensajeria: 'Mensajería',
    nav_sst: 'SST',
    nav_bioseguridad: 'Bioseguridad',
    nav_procedimientos_vet: 'Procedimientos Vet',
    nav_certificaciones: 'Certificaciones',
    nav_trazabilidad: 'Trazabilidad',
    nav_estadisticas: 'Estadísticas',
    nav_recomendaciones: 'Recomendaciones',
    nav_reportes: 'Reportes',
    nav_cumplimiento: 'Cumplimiento',
    nav_admin_sistema: 'Admin Sistema',
    nav_configuracion: 'Configuración',
    nav_personalizar: 'Personalizar',
    nav_respaldos: 'Respaldos',

    // -- Sections --
    sec_produccion: 'PRODUCCIÓN',
    sec_especies: 'ESPECIES',
    sec_gestion: 'GESTIÓN',
    sec_analisis: 'ANÁLISIS',
    sec_sistema: 'SISTEMA',

    // -- Common actions --
    crear: 'Crear',
    editar: 'Editar',
    eliminar: 'Eliminar',
    guardar: 'Guardar',
    cancelar: 'Cancelar',
    buscar: 'Buscar',
    exportar: 'Exportar',
    importar: 'Importar',
    descargar: 'Descargar',
    restaurar: 'Restaurar',
    enviar: 'Enviar',
    generar: 'Generar',
    probar: 'Probar',
    conectar: 'Conectar',
    actualizar: 'Actualizar',
    regenerar: 'Regenerar',
    nuevo: 'Nuevo',
    nueva: 'Nueva',
    cerrar: 'Cerrar',
    si: 'Sí',
    no: 'No',
    confirmar: 'Confirmar',
    accion: 'Acción',
    acciones: 'Acciones',
    cargando: 'Cargando...',
    sin_datos: 'Sin datos',
    error: 'Error',
    exito: 'Éxito',
    advertencia: 'Advertencia',
    informacion: 'Información',
    total: 'Total',
    fecha: 'Fecha',
    tipo: 'Tipo',
    nombre: 'Nombre',
    descripcion: 'Descripción',
    estado: 'Estado',
    codigo: 'Código',
    cantidad: 'Cantidad',
    precio: 'Precio',
    valor: 'Valor',
    categoria: 'Categoría',
    nota: 'Nota',
    observaciones: 'Observaciones',

    // -- Status labels --
    activo: 'Activo',
    inactivo: 'Inactivo',
    programado: 'Programado',
    completado: 'Completado',
    pendiente: 'Pendiente',
    cancelado: 'Cancelado',
    en_proceso: 'En Proceso',
    finalizado: 'Finalizado',
    leida: 'Leída',
    no_leida: 'No leída',
    resuelta: 'Resuelta',
    no_resuelta: 'No resuelta',
    configurado: 'Configurado',
    no_configurado: 'No configurado',

    // -- Severities --
    critica: 'Crítica',
    alta: 'Alta',
    media: 'Media',
    baja: 'Baja',

    // -- Login --
    login_titulo: 'AgroP',
    login_subtitulo: 'Sistema de Gestión Agropecuaria',
    login_email: 'Email',
    login_password: 'Contraseña',
    login_ingresar: 'Ingresar',
    login_error: 'Credenciales inválidas',
    login_placeholder_email: 'admin@agrop.local',
    login_placeholder_password: 'Tu contraseña',
    login_hint: 'admin@agrop.local / admin123',

    // -- Dashboard --
    dashboard_titulo: 'Dashboard',
    bienvenido: 'Bienvenido',
    bienvenido_usuario: 'Bienvenido, {nombre}',
    asistente_ia: 'Asistente IA',
    escanear: 'Escanear',
    total_animales: 'Total Animales',
    cultivos_activos: 'Cultivos Activos',
    siembras_activas: 'Siembras Activas',
    balance_mes: 'Balance del Mes',
    alertas_sin_leer: 'Alertas Sin Leer',
    actividad_reciente: 'Actividad Reciente',
    sin_actividad: 'Sin actividad reciente',
    widgets_reordenar: 'Reordenar widgets',
    alertas_requieren_atencion: 'Requieren atención',
    sin_pesaje_60d: '+60 días sin registrar',
    vacunas_proximas: 'vacunas próximas',
    programadas_pendientes: 'Programadas pendientes',
    cosechas_activas: 'cosechas activas',
    cultivos_en_produccion: 'Cultivos en producción',
    alertas_sin_leer_label: 'alertas sin leer',
    sin_pesaje_label: 'sin pesaje',

    // -- Dashboard widgets --
    widget_resumen_financiero: 'Resumen Financiero',
    widget_salud_hato: 'Salud del Hato',
    widget_cultivos_activos: 'Cultivos Activos',
    widget_inventario_critico: 'Inventario Crítico',
    widget_proximas_actividades: 'Próximas Actividades',
    widget_alertas_recientes: 'Alertas Recientes',
    widget_clima: 'Clima',
    widget_mapa_rapido: 'Mapa Rápido',
    ingresos: 'Ingresos',
    gastos: 'Gastos',
    balance: 'Balance',
    enfermos: 'Enfermos',
    vacunas_pend: 'Vacunas Pend.',
    mortalidad: 'Mortalidad',
    alertas_sanitarias: 'Alertas Sanitarias',
    sin_alertas_activas: 'Sin alertas activas',
    area_cultivada: 'Área Cultivada',
    proximas_cosechas: 'Próximas Cosechas',
    insumos_criticos: 'Sin insumos críticos',
    sin_actividades_pendientes: 'Sin actividades pendientes',
    sin_alertas_pendientes: 'Sin alertas pendientes',
    sin_registro_climatico: 'Sin registro climático',
    lluvia: 'Lluvia',
    temperatura: 'Temperatura',
    humedad: 'Humedad',
    distribucion_gastos: 'Distribución de Gastos',
    mortalidad_especie: 'Mortalidad por Especie',
    sin_datos_financieros: 'Sin datos financieros',

    // -- Time ranges --
    time_hoy: 'Hoy',
    time_semana: 'Esta semana',
    time_mes: 'Este mes',
    time_trimestre: 'Este trimestre',

    // -- Animals --
    animales_titulo: 'Animales',
    animal_nuevo: 'Nuevo Animal',
    animal_editar: 'Editar Animal',
    animal_codigo: 'Código',
    animal_nombre: 'Nombre',
    animal_especie: 'Especie',
    animal_sexo: 'Sexo',
    animal_raza: 'Raza',
    animal_grupo_manejo: 'Grupo Manejo',
    animal_origen: 'Origen',
    animal_chapeta: 'Chapeta',
    animal_microchip: 'Microchip',
    animal_color: 'Color',
    animal_peso: 'Peso',
    animal_fecha_nacimiento: 'F. Nacimiento',
    animal_fecha_ingreso: 'F. Ingreso',
    animal_eventos: 'Eventos',
    animal_ficha: 'Ficha',
    hembra: 'Hembra',
    macho: 'Macho',
    propio: 'Propio',
    prestamo: 'Préstamo',
    adopcion: 'Adopción',
    consignacion: 'Consignación',
    exportar_csv: 'Exportar',
    vacuna_proxima: 'Vacuna próxima a vencer',

    // -- Crops --
    cultivos_titulo: 'Cultivos',
    siembra_nueva: 'Nueva Siembra',
    siembra_editar: 'Editar Siembra',
    cultivo: 'Cultivo',
    variedad: 'Variedad',
    lote: 'Lote',
    fecha_siembra: 'Fecha Siembra',
    fecha_cosecha_estimada: 'Fecha Cosecha Estimada',
    area_ha: 'Área (ha)',
    semilla: 'Semilla',
    metodo_siembra: 'Método Siembra',
    rendimiento: 'Rendimiento',
    activo: 'Activo',
    cosechado: 'Cosechado',
    perdido: 'Perdido',
    planificado: 'Planificado',
    directa: 'Directa',
    trasplante: 'Trasplante',
    voleo: 'Voleo',
    surcos: 'Surcos',
    registrar_cosecha: 'Registrar Cosecha',
    cantidad_kg: 'Cantidad (kg)',
    calidad: 'Calidad',
    destino: 'Destino',

    // -- Lots --
    lotes_titulo: 'Lotes y Mapas',
    lote_nuevo: 'Nuevo Lote',
    lote_editar: 'Editar Lote',
    lote_nombre: 'Nombre',
    lote_area: 'Área (ha)',
    lote_uso: 'Uso Actual',
    lote_suelo: 'Tipo Suelo',
    lote_riego: 'Sistema Riego',
    cultivo: 'Cultivo',
    pastoreo: 'Pastoreo',
    bosque: 'Bosque',
    descanso: 'Descanso',
    construccion: 'Construcción',
    secano: 'Secano',
    aspersion: 'Aspersión',
    goteo: 'Goteo',
    gravedad: 'Gravedad',
    color_verde: 'Verde',
    color_verde_claro: 'Verde Claro',
    color_amarillo: 'Amarillo',
    color_naranja: 'Naranja',
    color_marron: 'Marrón',

    // -- Finances --
    finanzas_titulo: 'Finanzas',
    contabilidad_titulo: 'Contabilidad',
    nomina_titulo: 'Nómina',
    ingreso: 'Ingreso',
    gasto: 'Gasto',
    venta: 'Venta',
    costo: 'Costo',
    factura: 'Factura',
    presupuesto: 'Presupuesto',

    // -- Alerts --
    alertas_titulo: 'Centro de Notificaciones y Alertas',
    alertas: 'Alertas',
    alerta_nueva: 'Alerta nueva',
    alerta_resuelta: 'Alerta resuelta',
    telegram: 'Telegram',
    email: 'Email',
    whatsapp: 'WhatsApp',
    webhooks: 'Webhooks',
    telegram_config: 'Configuración de Telegram',
    email_config: 'Configuración de Email (SMTP)',
    whatsapp_config: 'Configuración de WhatsApp API',
    bot_token: 'Bot Token',
    chat_id: 'Chat ID',
    bot_token_desc: 'Token del bot de Telegram (obtenido de @BotFather)',
    chat_id_desc: 'ID del chat o grupo donde se enviarán las notificaciones',
    smtp_host: 'SMTP Host',
    smtp_port: 'SMTP Port',
    smtp_user: 'Usuario',
    smtp_password: 'Contraseña',
    from_email: 'Correo From',
    api_url: 'API URL',
    api_key: 'API Key',
    phone_number: 'Número de teléfono',
    guardar_config: 'Guardar Configuración',
    probar_conexion: 'Probar Conexión',
    enviar_alertas: 'Enviar Alertas Pendientes',
    enviar_alertas_email: 'Enviar Alertas por Email',
    enviar_alertas_whatsapp: 'Enviar Alertas por WhatsApp',
    sin_webhooks: 'Sin webhooks configurados',
    nuevo_webhook: 'Nuevo Webhook',
    editar_webhook: 'Editar Webhook',
    webhook_url: 'URL',
    webhook_eventos: 'Eventos',
    conectado: 'Conectado',
    config_guardada: 'Configuración guardada',
    mensaje_prueba_enviado: 'Mensaje de prueba enviado correctamente',
    error_conexion_telegram: 'No se pudo enviar el mensaje de prueba. Verifica token y chat ID.',
    sin_leer: 'Sin leer',
    criticas_sin_resolver: 'Críticas sin resolver',
    resueltas_hoy: 'Resueltas hoy',
    filtro_tipo: 'Tipo',
    filtro_severidad: 'Severidad',
    filtro_leida: 'Leída',
    filtro_resuelta: 'Resuelta',
    evento_alerta_nueva: 'Alerta nueva',
    evento_alerta_resuelta: 'Alerta resuelta',
    evento_inventario_bajo: 'Inventario bajo',
    evento_cosecha_vencida: 'Cosecha vencida',
    evento_vacuna_proxima: 'Vacuna próxima',

    // -- Backup --
    backup_titulo: 'Respaldos y Exportación',
    ultimo_backup: 'Último Backup',
    tamano_total: 'Tamaño Total',
    tablas_respaldadas: 'Tablas Respaldadas',
    crear_backup: 'Crear Backup Ahora',
    exportar_datos: 'Exportar Datos Completo',
    backup_disponibles: 'Respaldos Disponibles',
    fecha_backup: 'Fecha',
    tipo_backup: 'Tipo',
    tamano: 'Tamaño',
    estado_backup: 'Estado',
    completado: 'Completado',
    fallido: 'Fallido',
    restaurar_advertencia: '¿Está seguro de restaurar este backup? Todos los datos actuales se perderán.',
    restaurar_titulo: 'Restaurar Backup',
    programar_backup: 'Programar Backup Automático',
    diario: 'Diario',
    semanal: 'Semanal',
    mensual: 'Mensual',
    nunca: 'Nunca',
    programacion_guardada: 'Programación guardada',
    export_json: 'Exportar JSON',
    progreso_backup: 'Creando backup...',

    // -- Errors --
    error_red: 'Error de conexión. Verifique su red.',
    error_servidor: 'Error del servidor. Intente nuevamente.',
    error_permiso: 'No tiene permiso para realizar esta acción.',
    error_campo_requerido: 'Este campo es requerido',
    error_no_encontrado: 'No encontrado',

    // -- Help --
    ayuda: 'Ayuda',
    tutorial: 'Tutorial',
    tour_guiado: 'Tour Guiado',
    modo_sencillo: 'Modo Sencillo',
    modo_sencillo_activo: '✨ Modo Sencillo activo',

    // -- User menu --
    perfil: 'Perfil',
    cerrar_sesion: 'Cerrar Sesión',
    cambiar_idioma: 'Idioma',
    vista_como: 'Vista como',
    fincas: 'Fincas',
    configuracion: 'Configuración',

    // -- Mobile --
    inicio: 'Inicio',
    animales: 'Animales',
    lotes_mobile: 'Lotes',
    vet: 'Vet',

    // -- Species --
    bovino: 'Bovino',
    bufalino: 'Bufalino',
    porcino: 'Porcino',
    aviar: 'Aviar',
    caprino: 'Caprino',
    ovino: 'Ovino',
    equino: 'Equino',
    canino: 'Canino',
    felino: 'Felino',
    apicola: 'Apícola',
    picicola: 'Picícola',

    // -- General --
    siembra: 'Siembra',
    cosecha: 'Cosecha',
    inventario: 'Inventario',
    empleado: 'Empleado',
    proveedor: 'Proveedor',
    cliente: 'Cliente',
    producto: 'Producto',
    servicio: 'Servicio',
    kg: 'kg',
    ha: 'ha',
    mm: 'mm',
    vs_mes_anterior: 'vs mes anterior',
  },

  en: {
    // -- Navigation --
    nav_dashboard: 'Dashboard',
    nav_ganaderia: 'Livestock',
    nav_cultivos: 'Crops',
    nav_lotes: 'Lots & Maps',
    nav_operaciones: 'Operations',
    nav_grupos_manejo: 'Management Groups',
    nav_plantillas: 'Templates',
    nav_planeacion: 'Planning',
    nav_equipos: 'Equipment',
    nav_alertas: 'Alerts',
    nav_farmacia: 'Pharmacy',
    nav_agua: 'Water',
    nav_alimentacion: 'Feed',
    nav_picicultura: 'Fish Farming',
    nav_suelos: 'Soils',
    nav_sensores: 'Sensors',
    nav_forestal: 'Forestry',
    nav_especies: 'Species',
    nav_consolidado: 'Consolidated',
    nav_contabilidad: 'Accounting',
    nav_nomina: 'Payroll',
    nav_inventario: 'Inventory',
    nav_trabajadores: 'Workers',
    nav_mensajeria: 'Messaging',
    nav_sst: 'H&S',
    nav_bioseguridad: 'Biosecurity',
    nav_procedimientos_vet: 'Vet Procedures',
    nav_certificaciones: 'Certifications',
    nav_trazabilidad: 'Traceability',
    nav_estadisticas: 'Statistics',
    nav_recomendaciones: 'Recommendations',
    nav_reportes: 'Reports',
    nav_cumplimiento: 'Compliance',
    nav_admin_sistema: 'System Admin',
    nav_configuracion: 'Settings',
    nav_personalizar: 'Customize',
    nav_respaldos: 'Backups',

    // -- Sections --
    sec_produccion: 'PRODUCTION',
    sec_especies: 'SPECIES',
    sec_gestion: 'MANAGEMENT',
    sec_analisis: 'ANALYSIS',
    sec_sistema: 'SYSTEM',

    // -- Common actions --
    crear: 'Create',
    editar: 'Edit',
    eliminar: 'Delete',
    guardar: 'Save',
    cancelar: 'Cancel',
    buscar: 'Search',
    exportar: 'Export',
    importar: 'Import',
    descargar: 'Download',
    restaurar: 'Restore',
    enviar: 'Send',
    generar: 'Generate',
    probar: 'Test',
    conectar: 'Connect',
    actualizar: 'Update',
    regenerar: 'Regenerate',
    nuevo: 'New',
    nueva: 'New',
    cerrar: 'Close',
    si: 'Yes',
    no: 'No',
    confirmar: 'Confirm',
    accion: 'Action',
    acciones: 'Actions',
    cargando: 'Loading...',
    sin_datos: 'No data',
    error: 'Error',
    exito: 'Success',
    advertencia: 'Warning',
    informacion: 'Information',
    total: 'Total',
    fecha: 'Date',
    tipo: 'Type',
    nombre: 'Name',
    descripcion: 'Description',
    estado: 'Status',
    codigo: 'Code',
    cantidad: 'Quantity',
    precio: 'Price',
    valor: 'Value',
    categoria: 'Category',
    nota: 'Note',
    observaciones: 'Observations',

    // -- Status labels --
    activo: 'Active',
    inactivo: 'Inactive',
    programado: 'Scheduled',
    completado: 'Completed',
    pendiente: 'Pending',
    cancelado: 'Cancelled',
    en_proceso: 'In Progress',
    finalizado: 'Finished',
    leida: 'Read',
    no_leida: 'Unread',
    resuelta: 'Resolved',
    no_resuelta: 'Unresolved',
    configurado: 'Configured',
    no_configurado: 'Not configured',

    // -- Severities --
    critica: 'Critical',
    alta: 'High',
    media: 'Medium',
    baja: 'Low',

    // -- Login --
    login_titulo: 'AgroP',
    login_subtitulo: 'Farm Management System',
    login_email: 'Email',
    login_password: 'Password',
    login_ingresar: 'Sign In',
    login_error: 'Invalid credentials',
    login_placeholder_email: 'admin@agrop.local',
    login_placeholder_password: 'Your password',
    login_hint: 'admin@agrop.local / admin123',

    // -- Dashboard --
    dashboard_titulo: 'Dashboard',
    bienvenido: 'Welcome',
    bienvenido_usuario: 'Welcome, {nombre}',
    asistente_ia: 'AI Assistant',
    escanear: 'Scan',
    total_animales: 'Total Animals',
    cultivos_activos: 'Active Crops',
    siembras_activas: 'Active Plantings',
    balance_mes: 'Monthly Balance',
    alertas_sin_leer: 'Unread Alerts',
    actividad_reciente: 'Recent Activity',
    sin_actividad: 'No recent activity',
    widgets_reordenar: 'Reorder widgets',
    alertas_requieren_atencion: 'Need attention',
    sin_pesaje_60d: '+60 days without weighing',
    vacunas_proximas: 'upcoming vaccines',
    programadas_pendientes: 'Scheduled pending',
    cosechas_activas: 'active harvests',
    cultivos_en_produccion: 'Crops in production',
    alertas_sin_leer_label: 'unread alerts',
    sin_pesaje_label: 'without weighing',

    // -- Dashboard widgets --
    widget_resumen_financiero: 'Financial Summary',
    widget_salud_hato: 'Herd Health',
    widget_cultivos_activos: 'Active Crops',
    widget_inventario_critico: 'Critical Inventory',
    widget_proximas_actividades: 'Upcoming Activities',
    widget_alertas_recientes: 'Recent Alerts',
    widget_clima: 'Weather',
    widget_mapa_rapido: 'Quick Map',
    ingresos: 'Income',
    gastos: 'Expenses',
    balance: 'Balance',
    enfermos: 'Sick',
    vacunas_pend: 'Pending Vacc.',
    mortalidad: 'Mortality',
    alertas_sanitarias: 'Health Alerts',
    sin_alertas_activas: 'No active alerts',
    area_cultivada: 'Cultivated Area',
    proximas_cosechas: 'Upcoming Harvests',
    insumos_criticos: 'No critical supplies',
    sin_actividades_pendientes: 'No pending activities',
    sin_alertas_pendientes: 'No pending alerts',
    sin_registro_climatico: 'No weather records',
    lluvia: 'Rain',
    temperatura: 'Temperature',
    humedad: 'Humidity',
    distribucion_gastos: 'Expense Distribution',
    mortalidad_especie: 'Mortality by Species',
    sin_datos_financieros: 'No financial data',

    // -- Time ranges --
    time_hoy: 'Today',
    time_semana: 'This week',
    time_mes: 'This month',
    time_trimestre: 'This quarter',

    // -- Animals --
    animales_titulo: 'Animals',
    animal_nuevo: 'New Animal',
    animal_editar: 'Edit Animal',
    animal_codigo: 'Code',
    animal_nombre: 'Name',
    animal_especie: 'Species',
    animal_sexo: 'Sex',
    animal_raza: 'Breed',
    animal_grupo_manejo: 'Group',
    animal_origen: 'Origin',
    animal_chapeta: 'Tag',
    animal_microchip: 'Microchip',
    animal_color: 'Color',
    animal_peso: 'Weight',
    animal_fecha_nacimiento: 'Birth Date',
    animal_fecha_ingreso: 'Entry Date',
    animal_eventos: 'Events',
    animal_ficha: 'Record',
    hembra: 'Female',
    macho: 'Male',
    propio: 'Own',
    prestamo: 'Loan',
    adopcion: 'Adoption',
    consignacion: 'Consignment',
    exportar_csv: 'Export CSV',
    vacuna_proxima: 'Upcoming vaccination',

    // -- Crops --
    cultivos_titulo: 'Crops',
    siembra_nueva: 'New Planting',
    siembra_editar: 'Edit Planting',
    cultivo: 'Crop',
    variedad: 'Variety',
    lote: 'Lot',
    fecha_siembra: 'Planting Date',
    fecha_cosecha_estimada: 'Est. Harvest Date',
    area_ha: 'Area (ha)',
    semilla: 'Seed',
    metodo_siembra: 'Planting Method',
    rendimiento: 'Yield',
    activo: 'Active',
    cosechado: 'Harvested',
    perdido: 'Lost',
    planificado: 'Planned',
    directa: 'Direct',
    trasplante: 'Transplant',
    voleo: 'Broadcast',
    surcos: 'Rows',
    registrar_cosecha: 'Record Harvest',
    cantidad_kg: 'Quantity (kg)',
    calidad: 'Quality',
    destino: 'Destination',

    // -- Lots --
    lotes_titulo: 'Lots & Maps',
    lote_nuevo: 'New Lot',
    lote_editar: 'Edit Lot',
    lote_nombre: 'Name',
    lote_area: 'Area (ha)',
    lote_uso: 'Current Use',
    lote_suelo: 'Soil Type',
    lote_riego: 'Irrigation System',
    pastoreo: 'Grazing',
    bosque: 'Forest',
    descanso: 'Fallow',
    construccion: 'Construction',
    secano: 'Rainfed',
    aspersion: 'Sprinkler',
    goteo: 'Drip',
    gravedad: 'Gravity',
    color_verde: 'Green',
    color_verde_claro: 'Light Green',
    color_amarillo: 'Yellow',
    color_naranja: 'Orange',
    color_marron: 'Brown',

    // -- Finances --
    finanzas_titulo: 'Finances',
    contabilidad_titulo: 'Accounting',
    nomina_titulo: 'Payroll',
    ingreso: 'Income',
    gasto: 'Expense',
    venta: 'Sale',
    costo: 'Cost',
    factura: 'Invoice',
    presupuesto: 'Budget',

    // -- Alerts --
    alertas_titulo: 'Notification & Alert Center',
    alertas: 'Alerts',
    alerta_nueva: 'New alert',
    alerta_resuelta: 'Alert resolved',
    telegram: 'Telegram',
    email: 'Email',
    whatsapp: 'WhatsApp',
    webhooks: 'Webhooks',
    telegram_config: 'Telegram Configuration',
    email_config: 'Email Configuration (SMTP)',
    whatsapp_config: 'WhatsApp API Configuration',
    bot_token: 'Bot Token',
    chat_id: 'Chat ID',
    bot_token_desc: 'Telegram bot token (obtained from @BotFather)',
    chat_id_desc: 'Chat or group ID where notifications will be sent',
    smtp_host: 'SMTP Host',
    smtp_port: 'SMTP Port',
    smtp_user: 'Username',
    smtp_password: 'Password',
    from_email: 'From Email',
    api_url: 'API URL',
    api_key: 'API Key',
    phone_number: 'Phone Number',
    guardar_config: 'Save Configuration',
    probar_conexion: 'Test Connection',
    enviar_alertas: 'Send Pending Alerts',
    enviar_alertas_email: 'Send Alerts via Email',
    enviar_alertas_whatsapp: 'Send Alerts via WhatsApp',
    sin_webhooks: 'No webhooks configured',
    nuevo_webhook: 'New Webhook',
    editar_webhook: 'Edit Webhook',
    webhook_url: 'URL',
    webhook_eventos: 'Events',
    conectado: 'Connected',
    config_guardada: 'Configuration saved',
    mensaje_prueba_enviado: 'Test message sent successfully',
    error_conexion_telegram: 'Could not send test message. Check token and chat ID.',
    sin_leer: 'Unread',
    criticas_sin_resolver: 'Unresolved Critical',
    resueltas_hoy: 'Resolved Today',
    filtro_tipo: 'Type',
    filtro_severidad: 'Severity',
    filtro_leida: 'Read',
    filtro_resuelta: 'Resolved',
    evento_alerta_nueva: 'New alert',
    evento_alerta_resuelta: 'Alert resolved',
    evento_inventario_bajo: 'Low inventory',
    evento_cosecha_vencida: 'Overdue harvest',
    evento_vacuna_proxima: 'Upcoming vaccine',

    // -- Backup --
    backup_titulo: 'Backups & Export',
    ultimo_backup: 'Last Backup',
    tamano_total: 'Total Size',
    tablas_respaldadas: 'Backed Up Tables',
    crear_backup: 'Create Backup Now',
    exportar_datos: 'Export Complete Data',
    backup_disponibles: 'Available Backups',
    fecha_backup: 'Date',
    tipo_backup: 'Type',
    tamano: 'Size',
    estado_backup: 'Status',
    completado: 'Completed',
    fallido: 'Failed',
    restaurar_advertencia: 'Are you sure you want to restore this backup? All current data will be lost.',
    restaurar_titulo: 'Restore Backup',
    programar_backup: 'Schedule Automatic Backup',
    diario: 'Daily',
    semanal: 'Weekly',
    mensual: 'Monthly',
    nunca: 'Never',
    programacion_guardada: 'Schedule saved',
    export_json: 'Export JSON',
    progreso_backup: 'Creating backup...',

    // -- Errors --
    error_red: 'Connection error. Check your network.',
    error_servidor: 'Server error. Try again.',
    error_permiso: 'You do not have permission for this action.',
    error_campo_requerido: 'This field is required',
    error_no_encontrado: 'Not found',

    // -- Help --
    ayuda: 'Help',
    tutorial: 'Tutorial',
    tour_guiado: 'Guided Tour',
    modo_sencillo: 'Simple Mode',
    modo_sencillo_activo: '✨ Simple Mode active',

    // -- User menu --
    perfil: 'Profile',
    cerrar_sesion: 'Logout',
    cambiar_idioma: 'Language',
    vista_como: 'View as',
    fincas: 'Farms',
    configuracion: 'Settings',

    // -- Mobile --
    inicio: 'Home',
    animales: 'Animals',
    lotes_mobile: 'Lots',
    vet: 'Vet',

    // -- Species --
    bovino: 'Bovine',
    bufalino: 'Buffalo',
    porcino: 'Porcine',
    aviar: 'Poultry',
    caprino: 'Caprine',
    ovino: 'Ovine',
    equino: 'Equine',
    canino: 'Canine',
    felino: 'Feline',
    apicola: 'Bee',
    picicola: 'Fish',

    // -- General --
    siembra: 'Planting',
    cosecha: 'Harvest',
    inventario: 'Inventory',
    empleado: 'Employee',
    proveedor: 'Supplier',
    cliente: 'Client',
    producto: 'Product',
    servicio: 'Service',
    kg: 'kg',
    ha: 'ha',
    mm: 'mm',
    vs_mes_anterior: 'vs previous month',
  },
}

if (typeof globalThis !== 'undefined') {
  globalThis.TRADUCCIONES = TRADUCCIONES
}
