-- AgroP - Seeds: Plan de Actividades (Planeacion)
-- 40+ actividades realistas para los proximos 6 meses
USE agrop;

INSERT INTO plan_actividades (finca_id, lote_id, animal_id, tipo_actividad, titulo, descripcion, fecha_programada, fecha_ejecucion, duracion_estimada, responsable, prioridad, estado, resultado, observaciones) VALUES
(2, 27, NULL, 'vacunacion', 'Vacunacion Aftosa - Potrero La Gloria', 'Aplicacion de vacuna contra fiebre aftosa a todo el hato del potrero.', '2026-05-02', '2026-05-02', 4, 'Dr. Carlos Ramirez', 'alta', 'completado', 'Aplicada a 4 bovinos sin complicaciones.', 'Ciclo I-2026.'),
(2, 28, NULL, 'vacunacion', 'Vacunacion Aftosa - Lote El Tesoro', 'Vacunacion aftosa semestral. Animales de levante.', '2026-05-03', '2026-05-03', 3, 'Dr. Carlos Ramirez', 'alta', 'completado', 'Aplicada a 3 novillas.', NULL),
(2, 29, NULL, 'vacunacion', 'Vacunacion Aftosa - Potrero Las Flores', 'Cobertura total del potrero.', '2026-05-04', NULL, 4, 'Dr. Carlos Ramirez', 'alta', 'vencido', NULL, 'No se completo por lluvias. Reprogramar.'),
(4, 9, NULL, 'desparasitacion', 'Desparasitacion bovinos - Corrales', 'Desparasitacion interna y externa del hato bovino en corrales.', '2026-05-05', '2026-05-05', 3, 'Dr. Carlos Ramirez', 'media', 'completado', 'Aplicado Ivermectina 1%. 5 bovinos tratados.', NULL),
(4, 9, NULL, 'desparasitacion', 'Desparasitacion porcinos - Corrales', 'Desparasitacion de cerdos en area de corrales.', '2026-05-06', NULL, 2, 'Dr. Carlos Ramirez', 'media', 'vencido', NULL, 'Se pospuso por falta de insumos.'),
(4, 9, NULL, 'pesaje', 'Pesaje mensual - bovinos Finca Magdalena', 'Registro de peso individual de todos los bovinos.', '2026-05-03', '2026-05-03', 6, 'Pedro Martinez', 'media', 'completado', 'Bovinos pesados. Promedio: 430 kg.', NULL),
(2, 27, NULL, 'pesaje', 'Pesaje mensual - Hacienda El Porvenir', 'Pesaje de todo el hato bovino de la finca.', '2026-05-04', '2026-05-04', 5, 'Andres Lopez', 'media', 'completado', '10 bovinos registrados. Promedio: 410 kg.', NULL),
(2, 27, NULL, 'rotacion', 'Rotacion - Potrero La Gloria a El Tesoro', 'Movimiento de bovinos a pastura fresca en Lote El Tesoro.', '2026-05-07', '2026-05-07', 3, 'Andres Lopez', 'baja', 'completado', '4 bovinos trasladados.', NULL),
(2, 29, NULL, 'rotacion', 'Rotacion - Las Flores a La Esperanza', 'Rotacion programada de potrero.', '2026-05-10', NULL, 3, 'Andres Lopez', 'baja', 'vencido', NULL, 'No se realizo. Reprogramar.'),
(4, 11, NULL, 'siembra', 'Siembra de maiz - Poligono 1', 'Siembra de maiz variedad ICA V-305 en 2.5 has.', '2026-05-01', '2026-05-01', 8, 'Julio Cesar Diaz', 'alta', 'completado', '2.5 ha sembradas.', NULL),
(4, 11, NULL, 'fertilizacion', 'Fertilizacion maiz - Poligono 1 (dia 20)', 'Primera fertilizacion del maiz con urea 46% a los 20 dias de siembra.', '2026-05-20', '2026-05-20', 4, 'Julio Cesar Diaz', 'media', 'completado', '150 kg de urea aplicados.', NULL),
(2, 30, NULL, 'fertilizacion', 'Fertilizacion pasto - Lote La Esperanza', 'Aplicacion de fertilizante NPK en potrero para renovacion de pastura.', '2026-05-25', NULL, 5, 'Andres Lopez', 'media', 'en_curso', '50% completado.', NULL),
(4, 9, NULL, 'marcacion', 'Mantenimiento tractor - Corrales', 'Cambio de aceite y filtros del tractor agricola.', '2026-05-08', '2026-05-08', 3, 'Mecanico Juan Perez', 'alta', 'completado', 'Aceite 15W-40 cambiado.', NULL),
(2, 27, NULL, 'marcacion', 'Mantenimiento motosierra - Potrero La Gloria', 'Afinado y ajuste de motosierra STIHL MS-250.', '2026-05-12', NULL, 2, 'Mecanico Juan Perez', 'media', 'vencido', NULL, 'Repuestos no disponibles.'),
(4, 9, NULL, 'inseminacion', 'IA - Brisa (BOV-005) segundo servicio', 'Inseminacion artificial de Brisa con pajuela Brahman Rojo.', '2026-05-28', NULL, 2, 'Dr. Carlos Ramirez', 'alta', 'programado', NULL, 'Sincronizacion iniciada el 24 de mayo.'),
(4, 9, NULL, 'parto', 'Parto estimado - Lucero (BOV-001)', 'Parto estimado segun fecha de servicio (10-feb). Gestion: 280 dias.', '2026-11-17', NULL, 2, 'Dr. Carlos Ramirez', 'critica', 'programado', NULL, 'Prenada confirmada por ecografia.'),
(4, 9, NULL, 'parto', 'Parto estimado - Estrella (BOV-002)', 'Parto estimado segun monta natural del 20-marzo.', '2026-12-25', NULL, 2, 'Dr. Carlos Ramirez', 'critica', 'programado', NULL, 'Prenada confirmada.'),
(2, 27, NULL, 'pesaje', 'Pesaje mensual junio - Potrero La Gloria', 'Pesaje de control mensual de bovinos en potrero.', '2026-06-02', NULL, 5, 'Andres Lopez', 'media', 'programado', NULL, NULL),
(4, 9, NULL, 'pesaje', 'Pesaje mensual junio - Finca Magdalena', 'Pesaje de todos los animales de la finca.', '2026-06-03', NULL, 6, 'Pedro Martinez', 'media', 'programado', NULL, NULL),
(2, 28, NULL, 'rotacion', 'Rotacion - El Tesoro a Las Flores', 'Rotacion de pastoreo programada.', '2026-06-05', NULL, 3, 'Andres Lopez', 'baja', 'programado', NULL, NULL),
(4, 11, NULL, 'fertilizacion', 'Fertilizacion maiz - Poligono 1 (dia 50)', 'Segunda fertilizacion del maiz. Aplicacion de KCl + Urea.', '2026-06-10', NULL, 4, 'Julio Cesar Diaz', 'media', 'programado', NULL, NULL),
(4, 12, NULL, 'siembra', 'Siembra de frijol - Poligono 2', 'Siembra de frijol caupi variedad ICA-Caucasia en 1.8 has.', '2026-06-15', NULL, 7, 'Julio Cesar Diaz', 'alta', 'programado', NULL, NULL),
(2, 29, NULL, 'desparasitacion', 'Desparasitacion trimestral - Las Flores', 'Desparasitacion interna/externa del hato en Potrero Las Flores.', '2026-06-16', NULL, 3, 'Dr. Carlos Ramirez', 'media', 'programado', NULL, NULL),
(2, 27, NULL, 'vacunacion', 'Vacunacion carbon sintomatico - La Gloria', 'Vacuna contra carbon sintomatico (mancha) a todos los bovinos.', '2026-06-20', NULL, 3, 'Dr. Carlos Ramirez', 'alta', 'programado', NULL, NULL),
(4, 7, NULL, 'marcacion', 'Mantenimiento bomba de riego - Alojamientos', 'Revision y mantenimiento preventivo de bomba de riego.', '2026-06-22', NULL, 4, 'Mecanico Juan Perez', 'alta', 'programado', NULL, NULL),
(2, 27, NULL, 'pesaje', 'Pesaje mensual julio - Potrero La Gloria', 'Pesaje de control mensual.', '2026-07-01', NULL, 5, 'Andres Lopez', 'media', 'programado', NULL, NULL),
(4, 9, NULL, 'pesaje', 'Pesaje mensual julio - Finca Magdalena', 'Pesaje mensual de todos los animales.', '2026-07-02', NULL, 6, 'Pedro Martinez', 'media', 'programado', NULL, NULL),
(4, 11, NULL, 'cosecha', 'Cosecha de maiz - Poligono 1', 'Cosecha del maiz sembrado en mayo. Estimado 4.5 ton/ha.', '2026-07-07', NULL, 10, 'Julio Cesar Diaz', 'alta', 'programado', NULL, NULL),
(2, 30, NULL, 'rotacion', 'Rotacion - La Esperanza a El Bosque', 'Rotacion de pastoreo programada.', '2026-07-10', NULL, 3, 'Andres Lopez', 'baja', 'programado', NULL, NULL),
(4, 12, NULL, 'fertilizacion', 'Fertilizacion frijol - Poligono 2 (dia 25)', 'Aplicacion de fertilizante foliar y edafico en cultivo de frijol.', '2026-07-11', NULL, 4, 'Julio Cesar Diaz', 'media', 'programado', NULL, NULL),
(2, 28, NULL, 'desparasitacion', 'Desparasitacion trimestral - El Tesoro', 'Desparasitacion de bovinos en Lote El Tesoro.', '2026-07-14', NULL, 3, 'Dr. Carlos Ramirez', 'media', 'programado', NULL, NULL),
(4, 13, NULL, 'siembra', 'Siembra de arroz - Poligono 3', 'Siembra de arroz variedad Fedearroz 2000 en 3.2 has.', '2026-07-20', NULL, 10, 'Julio Cesar Diaz', 'alta', 'programado', NULL, NULL),
(2, 27, NULL, 'pesaje', 'Pesaje mensual agosto - Potrero La Gloria', 'Pesaje rutinario del hato.', '2026-08-03', NULL, 5, 'Andres Lopez', 'media', 'programado', NULL, NULL),
(4, 9, NULL, 'pesaje', 'Pesaje mensual agosto - Finca Magdalena', 'Pesaje de finca, incluir bufalos.', '2026-08-04', NULL, 7, 'Pedro Martinez', 'media', 'programado', NULL, NULL),
(4, 9, NULL, 'vacunacion', 'Vacunacion Aftosa ciclo II-2026 - Finca Magdalena', 'Vacunacion aftosa semestral a todo el hato bovino y bufalino.', '2026-08-05', NULL, 5, 'Dr. Carlos Ramirez', 'alta', 'programado', NULL, NULL),
(2, 27, NULL, 'vacunacion', 'Vacunacion Aftosa ciclo II-2026 - Hacienda El Porvenir', 'Vacunacion aftosa a todos los bovinos de la finca.', '2026-08-06', NULL, 4, 'Dr. Carlos Ramirez', 'alta', 'programado', NULL, NULL),
(2, 31, NULL, 'rotacion', 'Rotacion - El Bosque a La Gloria', 'Retorno de bovinos a potrero principal.', '2026-08-08', NULL, 3, 'Andres Lopez', 'baja', 'programado', NULL, NULL),
(4, 11, NULL, 'fertilizacion', 'Encalado - Poligono 1 (post-cosecha)', 'Aplicacion de cal agricola para correccion de pH del suelo.', '2026-08-12', NULL, 5, 'Julio Cesar Diaz', 'media', 'programado', NULL, NULL),
(2, 29, NULL, 'marcacion', 'Mantenimiento tractor - Potrero Las Flores', 'Mantenimiento preventivo: revision de frenos y sistema hidraulico.', '2026-08-18', NULL, 5, 'Mecanico Juan Perez', 'alta', 'programado', NULL, NULL),
(4, 12, NULL, 'cosecha', 'Cosecha de frijol - Poligono 2', 'Cosecha del frijol caupi sembrado en junio.', '2026-08-20', NULL, 8, 'Julio Cesar Diaz', 'alta', 'programado', NULL, NULL),
(2, 28, NULL, 'desparasitacion', 'Desparasitacion trimestral - El Tesoro', 'Desparasitacion trimestral de rutina.', '2026-08-25', NULL, 3, 'Dr. Carlos Ramirez', 'media', 'programado', NULL, NULL),
(2, 27, NULL, 'pesaje', 'Pesaje mensual septiembre - Potrero La Gloria', 'Pesaje mensual de bovinos.', '2026-09-02', NULL, 5, 'Andres Lopez', 'media', 'programado', NULL, NULL),
(4, 9, NULL, 'pesaje', 'Pesaje mensual septiembre - Finca Magdalena', 'Pesaje mensual general.', '2026-09-03', NULL, 6, 'Pedro Martinez', 'media', 'programado', NULL, NULL),
(4, 13, NULL, 'fertilizacion', 'Fertilizacion arroz - Poligono 3 (dia 45)', 'Fertilizacion del arroz en etapa de macollamiento.', '2026-09-05', NULL, 4, 'Julio Cesar Diaz', 'media', 'programado', NULL, NULL),
(2, 30, NULL, 'rotacion', 'Rotacion - La Esperanza a Las Flores', 'Rotacion de pastoreo.', '2026-09-07', NULL, 3, 'Andres Lopez', 'baja', 'programado', NULL, NULL),
(4, 9, NULL, 'desparasitacion', 'Desparasitacion trimestral - Finca Magdalena', 'Desparasitacion de todos los animales de la finca.', '2026-09-10', NULL, 5, 'Dr. Carlos Ramirez', 'media', 'programado', NULL, NULL),
(4, 14, NULL, 'siembra', 'Siembra de yuca - Poligono 4', 'Siembra de yuca industrial variedad ICA-Costera en 2.0 has.', '2026-09-15', NULL, 8, 'Julio Cesar Diaz', 'alta', 'programado', NULL, NULL),
(2, 27, NULL, 'marcacion', 'Mantenimiento cerca electrica - Potrero La Gloria', 'Revision y reparacion de cerca electrica perimetral.', '2026-09-18', NULL, 4, 'Andres Lopez', 'media', 'programado', NULL, NULL),
(4, 7, NULL, 'riego', 'Riego de emergencia - Alojamientos', 'Riego programado en germinacion de nuevos cultivos.', '2026-09-22', NULL, 3, 'Julio Cesar Diaz', 'baja', 'programado', NULL, NULL),
(2, 27, NULL, 'pesaje', 'Pesaje mensual octubre - Potrero La Gloria', 'Pesaje mensual.', '2026-10-01', NULL, 5, 'Andres Lopez', 'media', 'programado', NULL, NULL),
(4, 9, NULL, 'pesaje', 'Pesaje mensual octubre - Finca Magdalena', 'Pesaje mensual general.', '2026-10-02', NULL, 6, 'Pedro Martinez', 'media', 'programado', NULL, NULL),
(4, 13, NULL, 'cosecha', 'Cosecha de arroz - Poligono 3', 'Cosecha de arroz sembrado en julio.', '2026-10-05', NULL, 12, 'Julio Cesar Diaz', 'alta', 'programado', NULL, NULL),
(2, 31, NULL, 'rotacion', 'Rotacion - El Bosque a La Esperanza', 'Rotacion de potrero.', '2026-10-08', NULL, 3, 'Andres Lopez', 'baja', 'programado', NULL, NULL),
(4, 11, NULL, 'siembra', 'Siembra de maiz segundo ciclo - Poligono 1', 'Segunda siembra del ano de maiz en Poligono 1.', '2026-10-12', NULL, 8, 'Julio Cesar Diaz', 'alta', 'programado', NULL, NULL),
(2, 28, NULL, 'desparasitacion', 'Desparasitacion trimestral - El Tesoro', 'Desparasitacion trimestral de bovinos.', '2026-10-15', NULL, 3, 'Dr. Carlos Ramirez', 'media', 'programado', NULL, NULL),
(4, 9, NULL, 'inseminacion', 'IA - Paloma (BOV-004) post-parto', 'Inseminacion artificial de Paloma tras 6 meses post-parto.', '2026-10-20', NULL, 2, 'Dr. Carlos Ramirez', 'alta', 'programado', NULL, NULL),
(4, 15, NULL, 'fertilizacion', 'Abonada potrero - Poligono 5', 'Aplicacion de abono organico compostado para renovacion.', '2026-10-25', NULL, 5, 'Julio Cesar Diaz', 'media', 'programado', NULL, NULL),
(2, 27, NULL, 'pesaje', 'Pesaje mensual noviembre - Potrero La Gloria', 'Pesaje de fin de periodo.', '2026-11-03', NULL, 5, 'Andres Lopez', 'media', 'programado', NULL, NULL),
(4, 9, NULL, 'pesaje', 'Pesaje mensual noviembre - Finca Magdalena', 'Pesaje general mensual.', '2026-11-04', NULL, 6, 'Pedro Martinez', 'media', 'programado', NULL, NULL),
(2, 29, NULL, 'rotacion', 'Rotacion - Las Flores a El Bosque', 'Rotacion programada de invierno.', '2026-11-06', NULL, 3, 'Andres Lopez', 'baja', 'programado', NULL, NULL),
(4, 11, NULL, 'fertilizacion', 'Fertilizacion maiz ciclo II - Poligono 1 (dia 30)', 'Fertilizacion del segundo ciclo de maiz.', '2026-11-10', NULL, 4, 'Julio Cesar Diaz', 'media', 'programado', NULL, NULL),
(2, 27, NULL, 'vacunacion', 'Vacunacion IBR - Potrero La Gloria', 'Vacunacion contra Rinotraqueitis Infecciosa Bovina a todo el hato.', '2026-11-12', NULL, 3, 'Dr. Carlos Ramirez', 'alta', 'programado', NULL, NULL),
(2, 30, NULL, 'marcacion', 'Mantenimiento general maquinaria - Hacienda', 'Revision general de tractores y equipos antes de temporada seca.', '2026-11-18', NULL, 6, 'Mecanico Juan Perez', 'alta', 'programado', NULL, NULL),
(4, 9, NULL, 'desparasitacion', 'Desparasitacion - Finca Magdalena (nov)', 'Desparasitacion de todos los animales. Incluir bufalos.', '2026-11-20', NULL, 5, 'Dr. Carlos Ramirez', 'media', 'programado', NULL, NULL),
(4, 14, NULL, 'cosecha', 'Cosecha de yuca - Poligono 4', 'Cosecha de yuca sembrada en septiembre. Estimado 12 ton.', '2026-11-25', NULL, 10, 'Julio Cesar Diaz', 'alta', 'programado', NULL, NULL);
